# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:

       - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            cd docs-src
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            bundle exec jekyll build
            cd ../
            REPO="$(git config --get remote.origin.url)"
            rm -rf .git
            cd docs/
            ls -lsa
            git config --global user.email "mgargano@gmail.com"
            git config --global user.name "Mat Gargano"
            git init
            git add .
            git commit -am "initial commit"
            git remote add origin $REPO
            pwd
            ./../docs-src/bin/add-branch-if-needed.sh
            git push origin -f gh-pages

      - save_cache:
          paths:
            - ./docs-src
          key: v1-dependencies-{{ checksum "./docs-src/Gemfile.lock" }}

      # run tests!
      - run:
          name: run tests
          command: |
            echo 'write tests'

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
general:
  branches:
    only:
     - master